const language: { [key: string]: { [key: string]: string } } = {
  login: {
    en: 'Login',
    es: 'Iniciar sesión',
    fr: 'Connexion',
    de: 'Anmeldung',
    it: 'Accesso',
    pt: 'Entrar',
    ru: 'Вход',
    ja: 'ログイン',
    ko: '로그인',
    zh: '登录',
  },
  username: {
    en: 'Username',
    es: 'Nombre de usuario',
    fr: "Nom d'utilisateur",
    de: 'Nutzername',
    it: 'Nome utente',
    pt: 'Nome de usuário',
    ru: 'Имя пользователя',
    ja: 'ユーザー名',
    ko: '사용자 이름',
    zh: '用户名',
  },
  password: {
    en: 'Password',
    es: 'Contraseña',
    fr: 'Mot de passe',
    de: 'Passwort',
    it: "Parola d'ordine",
    pt: 'Senha',
    ru: 'Пароль',
    ja: 'パスワード',
    ko: '비밀번호',
    zh: '密码',
  },
  'confirm password': {
    en: 'Confirm Password',
    es: 'Confirmar contraseña',
    fr: 'Confirmer le mot de passe',
    de: 'Passwort bestätigen',
    it: 'Conferma password',
    pt: 'Confirme a senha',
    ru: 'Подтвердите пароль',
    ja: 'パスワードを確認',
    ko: '비밀번호 확인',
    zh: '确认密码',
  },
  register: {
    en: 'Register',
    es: 'Registrarse',
    fr: "S'inscrire",
    de: 'Registrieren',
    it: 'Iscriviti',
    pt: 'Registro',
    ru: 'Регистрация',
    ja: '登録',
    ko: '회원가입',
    zh: '注册',
  },
  'goto register': {
    en: 'Go to register',
    es: 'Ir a registrarse',
    fr: "Aller à l'inscription",
    de: 'Zur Registrierung gehen',
    it: 'Vai alla registrazione',
    pt: 'Ir para o registro',
    ru: 'Перейти к регистрации',
    ja: '登録に進む',
    ko: '회원가입으로',
    zh: '去注册',
  },
  'goto login': {
    en: 'Go to login',
    es: 'Ir a iniciar sesión',
    fr: 'Aller à la connexion',
    de: 'Zur Anmeldung gehen',
    it: 'Vai al login',
    pt: 'Ir para o login',
    ru: 'Перейти к входу',
    ja: 'ログインに進む',
    ko: '로그인으로',
    zh: '去登录',
  },
  logout: {
    en: 'Logout',
    es: 'Cerrar sesión',
    fr: 'Se déconnecter',
    de: 'Ausloggen',
    it: 'Disconnetters',
    pt: 'Sair',
    ru: 'Выйти',
    ja: 'ログアウト',
    ko: '로그아웃',
    zh: '登出',
  },
  'failed to login': {
    en: 'Failed to login',
    es: 'Error al iniciar sesión',
    fr: 'Échec de la connexion',
    de: 'Anmeldung fehlgeschlagen',
    it: 'Accesso fallito',
    pt: 'Falha ao entrar',
    ru: 'Ошибка входа',
    ja: 'ログインに失敗しました',
    ko: '로그인에 실패했습니다',
    zh: '登录失败',
  },
  'failed to register': {
    en: 'Failed to register',
    es: 'Error al registrarse',
    fr: "Échec de l'inscription",
    de: 'Registrierung fehlgeschlagen',
    it: 'Registrazione fallita',
    pt: 'Falha ao registrar',
    ru: 'Ошибка регистрации',
    ja: '登録に失敗しました',
    ko: '회원가입에 실패했습니다',
    zh: '注册失败',
  },
  'username already exists': {
    en: 'Username already exists',
    es: 'Nombre de usuario ya existe',
    fr: "Nom d'utilisateur déjà existant",
    de: 'Benutzername existiert bereits',
    it: 'Nome utente già esistente',
    pt: 'Nome de usuário já existe',
    ru: 'Имя пользователя уже существует',
    ja: 'ユーザー名はすでに存在します',
    ko: '사용자 이름이 이미 존재합니다',
    zh: '用户名已经存在',
  },
  'invalid username or password': {
    en: 'Invalid username or password',
    es: 'Nombre de usuario o contraseña inválidos',
    fr: "Nom d'utilisateur ou mot de passe invalide",
    de: 'Ungültiger Benutzername oder Passwort',
    it: 'Nome utente o password non validi',
    pt: 'Nome de usuário ou senha inválidos',
    ru: 'Неверное имя пользователя или пароль',
    ja: '無効なユーザー名またはパスワード',
    ko: '잘못된 사용자 이름 또는 비밀번호',
    zh: '用户名或密码无效',
  },
  'invalid username': {
    en: 'Invalid username',
    es: 'Nombre de usuario inválido',
    fr: "Nom d'utilisateur invalide",
    de: 'Ungültiger Benutzername',
    it: 'Nome utente non valido',
    pt: 'Nome de usuário inválido',
    ru: 'Неверное имя пользователя',
    ja: '無効なユーザー名',
    ko: '잘못된 사용자 이름',
    zh: '无效的用户名',
  },
  'invalid password': {
    en: 'Invalid password',
    es: 'Contraseña inválida',
    fr: 'Mot de passe invalide',
    de: 'Ungültiges Passwort',
    it: 'Password non valida',
    pt: 'Senha inválida',
    ru: 'Неверный пароль',
    ja: '無効なパスワード',
    ko: '잘못된 비밀번호',
    zh: '无效的密码',
  },
  'passwords do not match': {
    en: 'Passwords do not match',
    es: 'Las contraseñas no coinciden',
    fr: 'Les mots de passe ne correspondent pas',
    de: 'Passwörter stimmen nicht überein',
    it: 'Le password non corrispondono',
    pt: 'Senhas não correspondem',
    ru: 'Пароли не совпадают',
    ja: 'パスワードが一致しません',
    ko: '비밀번호가 일치하지 않습니다',
    zh: '密码不匹配',
  },
  rank: {
    en: 'Rank',
    es: 'Rango',
    fr: 'Rang',
    de: 'Rang',
    it: 'Rango',
    pt: 'Classificação',
    ru: 'Ранг',
    ja: 'ランク',
    ko: '랭킹',
    zh: '排名',
  },
  clan: {
    en: 'Clan',
    es: 'Clan',
    fr: 'Clan',
    de: 'Clan',
    it: 'Clan',
    pt: 'Clã',
    ru: 'Клан',
    ja: 'クラン',
    ko: '클랜',
    zh: '氏族',
  },
  play: {
    en: 'Play',
    es: 'Jugar',
    fr: 'Jouer',
    de: 'Spielen',
    it: 'Giocare',
    pt: 'Jogar',
    ru: 'Играть',
    ja: '遊ぶ',
    ko: '플레이',
    zh: '玩',
  },
  profile: {
    en: 'Profile',
    es: 'Perfil',
    fr: 'Profil',
    de: 'Profil',
    it: 'Profilo',
    pt: 'Perfil',
    ru: 'Профиль',
    ja: 'プロフィール',
    ko: '프로필',
    zh: '个人资料',
  },
  shop: {
    en: 'Shop',
    es: 'Tienda',
    fr: 'Magasin',
    de: 'Geschäft',
    it: 'Negozio',
    pt: 'Loja',
    ru: 'Магазин',
    ja: 'ショップ',
    ko: '상점',
    zh: '商店',
  },
  settings: {
    en: 'Settings',
    es: 'Ajustes',
    fr: 'Paramètres',
    de: 'Einstellungen',
    it: 'Impostazioni',
    pt: 'Configurações',
    ru: 'Настройки',
    ja: '設定',
    ko: '설정',
    zh: '设置',
  },
  rooms: {
    en: 'Rooms',
    es: 'Salas',
    fr: 'Salles',
    de: 'Räume',
    it: 'Stanze',
    pt: 'Salas',
    ru: 'Комнаты',
    ja: '部屋',
    ko: '방',
    zh: '房间',
  },
  create: {
    en: 'Create',
    es: 'Crear',
    fr: 'Créer',
    de: 'Erstellen',
    it: 'Creare',
    pt: 'Crio',
    ru: 'Создать',
    ja: '作成',
    ko: '생성',
    zh: '创建',
  },
  'room name': {
    en: 'Room name',
    es: 'Nombre de la sala',
    fr: 'Nom de la salle',
    de: 'Raumname',
    it: 'Nome della stanza',
    pt: 'Nome da sala',
    ru: 'Название комнаты',
    ja: '部屋名',
    ko: '방 이름',
    zh: '房间名',
  },
  'max players': {
    en: 'Max players',
    es: 'Jugadores máximos',
    fr: 'Joueurs max',
    de: 'Maximale Spieler',
    it: 'Giocatori massimi',
    pt: 'Jogadores máximos',
    ru: 'Максимальное количество игроков',
    ja: '最大プレイヤー数',
    ko: '최대 플레이어',
    zh: '最大玩家',
  },
  private: {
    en: 'Private',
    es: 'Privado',
    fr: 'Privé',
    de: 'Privat',
    it: 'Privato',
    pt: 'Privado',
    ru: 'Частный',
    ja: 'プライベート',
    ko: '비공개',
    zh: '私人的',
  },
  'invalid room name': {
    en: 'Invalid room name',
    es: 'Nombre de sala inválido',
    fr: 'Nom de salle invalide',
    de: 'Ungültiger Raumname',
    it: 'Nome stanza non valido',
    pt: 'Nome da sala inválido',
    ru: 'Недопустимое имя комнаты',
    ja: '無効な部屋名',
    ko: '잘못된 방 이름',
    zh: '无效的房间名',
  },
  'invalid max players': {
    en: 'Invalid max players',
    es: 'Jugadores máximos inválidos',
    fr: 'Joueurs max invalides',
    de: 'Ungültige maximale Spieler',
    it: 'Giocatori massimi non validi',
    pt: 'Jogadores máximos inválidos',
    ru: 'Недопустимое количество игроков',
    ja: '無効な最大プレイヤー数',
    ko: '잘못된 최대 플레이어',
    zh: '无效的最大玩家',
  },
  'room is full': {
    en: 'Room is full',
    es: 'La sala está llena',
    fr: 'La salle est pleine',
    de: 'Raum ist voll',
    it: 'La stanza è piena',
    pt: 'Sala cheia',
    ru: 'Комната заполнена',
    ja: '部屋がいっぱいです',
    ko: '방이 꽉 찼습니다',
    zh: '房间已满',
  },
  'room not found': {
    en: 'Room not found',
    es: 'Sala no encontrada',
    fr: 'Salle non trouvée',
    de: 'Raum nicht gefunden',
    it: 'Stanza non trovata',
    pt: 'Sala não encontrada',
    ru: 'Комната не найдена',
    ja: '部屋が見つかりません',
    ko: '방을 찾을 수 없습니다',
    zh: '找不到房间',
  },
  'chat messages': {
    en: 'Chat messages',
    es: 'Mensajes de chat',
    fr: 'Messages de chat',
    de: 'Chatnachrichten',
    it: 'Messaggi di chat',
    pt: 'Mensagens de bate-papo',
    ru: 'Сообщения чата',
    ja: 'チャットメッセージ',
    ko: '채팅 메시지',
    zh: '聊天消息',
  },
  leave: {
    en: 'Leave',
    es: 'Dejar',
    fr: 'Partir',
    de: 'Verlassen',
    it: 'Partire',
    pt: 'Sair',
    ru: 'Покинуть',
    ja: '去る',
    ko: '나가기',
    zh: '离开',
  },
  start: {
    en: 'Start',
    es: 'Comienzo',
    fr: 'Début',
    de: 'Start',
    it: 'Inizio',
    pt: 'Começo',
    ru: 'Старт',
    ja: '開始',
    ko: '시작',
    zh: '开始',
  },
};

export const langOf = (lang: string, key: string) => {
  return language[key] ? language[key][lang] || language[key]['en'] : key;
};
